
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/course_arrange
  thymeleaf:
    cache: false
    # 配置前缀
    prefix: classpath:/templates/
    # 配置后缀
    suffix: .html

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

